services:
  db:
    build: ./databases
    container_name: databases
    ports:
      - "${DATABASES_PORT}:${DATABASES_PORT}"
    volumes:
      - prophecy:/var/lib/postgresql/data
    environment:
      - "POSTGRES_DB"
      - "POSTGRES_USER"
      - "POSTGRES_PASSWORD"
    networks:
      - prophecy
  
  server:
    depends_on:
      - "db"
    build: .
    container_name: nestjs-server
    command: ["yarn", "start"]
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    networks:
      - prophecy

  tests:
      depends_on:
        - "db"
        - "server"
      image: backend_server
      container_name: backend_tests
      command: ["yarn", "test"]
      ports:
        - "${TESTS_PORT}"

volumes:
  prophecy:

networks:
  prophecy:
