Project Prophecy_Activities
{
    database_type: 'PostgreSQL'
}

Table locations
{
    id              varchar     [pk, not null, unique]
    owner           varchar     [fk, ref: > Prophecy_Users.profile.username, not null]
    name            varchar     [not null]
    description     varchar
    address         varchar     [not null]
    website         varchar
    email           varchar
    phone           varchar
}

Table events
{
    id              varchar     [pk, not null]
    location        varchar     [fk, ref: > locations.id, not null]
    organiser       varchar     [fk, ref > Prophecy_Users.profile.username, not null]
    name            varchar     [not null]
    description     varchar
    date_time       timestamp   [not null]
    link            varchar
}