Project Prophecy_Activities
{
    database_type: 'PostgreSQL'
}

Table credentials
{
    name            varchar     [pk, unique, not null]
}

Table composition
{
    name            varchar     [not null]
    limit           varchar     [not null]
    type            varchar     [not null]
}

Table units
{
    army            varchar     [pk, ref: > credentials.name, not null]
    name            varchar     [unique, not null]
    height          varchar     [not null]
    type            varchar     [not null]
    base            varchar     [not null]
    cost            int         [not null]
    extraModelCost  int            
    adv             varchar
    mar             varchar     
    dis             varchar
    globalRules     varchar     [pk, ref: < rules.name]
    att             varchar
    off             varchar
    str             varchar
    ap              varchar
    agi             varchar
    offensiveRules  varchar     [pk, ref: < rules.name]
    hp              varchar
    def             varchar
    res             varchar
    arm             varchar
    aegis           varchar
    defensiveRules  varchar     [pk, ref: < rules.name]
    rules           varchar     [pk, ref: > rules.name]
    modifiers       varchar     [pk, ref: > modifiers.name]
}

Table rules
{
    name            varchar     [pk, not null, unique]
    description     varchar
    modifiers       varchar     [pk]
    unit            varchar     [pk]
}

Table modifiers
{
    name            varchar     [pk]
    cost            int         [not null]
    adv             varchar
    mar             varchar     
    dis             varchar
    att             varchar
    off             varchar
    str             varchar
    ap              varchar
    agi             varchar
    hp              varchar
    def             varchar
    res             varchar
    arm             varchar
    aegis           varchar
}