Project Prophecy_Users
{
    database_type: 'PostgreSQL'
}

Table profile
{
    username                varchar             [pk, not null, unique]
    email                   varchar             [not null, unique]
    password                varbinary           [not null]
    is_verified             bool                [default: false]
    profile_picture_path    varchar             [note: "profile pictures are not stored in the database"]
}

Table followers
{
    followers               varchar             [pk, ref: > profile.username]
    followee                varchar             [pk, ref: > profile.username]
}

Table blocked
{
    blocker                 varchar             [pk, ref: > profile.username]
    blockee                 varchar             [pk, ref: > profile.username]
}

Enum shared_items_type
{
    army_list
    game
    statistic
}

Table shared_items
{
    owner                   varchar             [pk, ref: > profile.username, not null, unique]
    type                    shared_items_type   [not null]
    ids                     varchar             [note: "ids are stored in the row, separated by ','
                                                    example: intemA,itemB,itemC"]
}


Table posts
{
    owner                   varchar             [pk, ref: > profile.username, not null, unique]
    id                      varchar             [not null, unique]
    description             varchar             
    path_to_content         varchar             [not null, 
                                                note: "pictures are not stored in the database"]
}
