Project Prophecy_Users
{
    database_type: 'PostgreSQL'
}

Table profile
{
    username                varchar             [not null, unique]
    email                   varchar             [not null, unique]
    password                varchar             [not null]
    is_verified             bool                [default: false]
    profile_picture_path    varchar             [note: "profile pictures are not stored in the database"]
    followed_users          varchar             [note: "usernames are stored in the row, separated by ','
                                                    example: userA,userB,userC"]
    followers               varchar             [note: "usernames are stored in the row, separated by ','
                                                    example: userA,userB,userC"]
    blocked_users           varchar             [note: "usernames are stored in the row, separated by ','
                                                    example: userA,userB,userC"]
}

Enum shared_items_type
{
    army_list
    game
    statistic
}

Table shared_items
{
    username                varchar             [not null, unique]
    type                    shared_items_type   [not null]
    ids                     varchar             [note: "ids are stored in the row, separated by ','
                                                    example: intemA,itemB,itemC"]
}

Table posts
{
    username                varchar             [not null, unique]
    id                      varchar             [not null, unique]
    description             varchar             
    path_to_content         varchar             [not null, 
                                                note: "pictures are not stored in the database"]
}
