swagger: "2.0"
info:
  description: |
    This is the Prophecy Api documentation
  version: 1.0.0
  title: "Prophecy Api"

# host: "localhost" # TODO: change

# basePath: "/api"

tags:
  - name: "account"
    description: "Everything about the user's account"
  - name: "events"
    description: "Everything about the events"
  - name: "armies"
    description: "Everything about the armies"
  - name: "prophecies"
    description: "Everything about the prophecies"
  - name: "statistics"
    description: "Everything about the statistics"
  - name: "settings"
    description: "Everything about the settings"
  - name: "users"
    description: "Everything about the users"
  - name: "units"
    description: "Everything about the units"
  - name: "teams"
    description: "Everything about the teams"

# schemes:
#   - "http"
#   - "https"


paths:

# Account: 

  /account/sign-in:
    post:
      parameters: # parameter content type: text
        - name: "username"
          in: "body"
          description: "The user's username"
          required: true
          type: "string"
        - name: "password"
          in: "body"
          description: "The user's password"
          required: true
          type: string
      tags: 
        - "account"
      summary: "Enables the user to sign in"      
      description: ""
      responses:
        # TODO
        
  /account/sign-up:
    put:
      parameters:
        # TODO
      tags: 
        - "account"
      summary: "Enables the user to create an account"
      description: ""
      responses: 
        # TODO
        
  /account/sign-out:
    post:
      parameters:
        # TODO
      tags:
        - "account"
      summary: "Enables the user to logout"
      description: ""
      responses:
        # TODO

# EVENTS

  # create
  /events/create-event:
    post:
      parameters:
        # TODO
      tags:
        - "events"
      summary: "Creates a new event"
      description: ""
      responses:
        # TODO
        
  /events/save-event/{eventId}:
    put:
      parameters:
        # TODO
      tags:
        - "events"
      summary: "Saves an event for the user"
      description: ""
      responses: 
        # TODO

  # read
  /events/get-events-list:
    get:
      parameters:
        #TODO
      tags:
        - "events"
      summary: "Retrieves the events list"
      description: ""
      responses:
        # TODO
        
  /events/get-event/{eventId}:
    get:
      parameters:
        # TODO
      tags:
        - "events"
      summary: "Retrieves an event data"
      description: ""
      responses:
        # TODO
  
  /events/get-saved-events-list:
    get:
      parameters:
        # TODO
      tags:
        - "events"
      summary: "Retrieves the saved events list"
      description: ""
      responses: 
        # TODO
  
  # update
  /event/update-event/{eventId}:
    put:
      parameters:
        # TODO
      tags:
        - "events"
      summary: "Updates an event's informations"
      description: ""
      responses:
        # TODO

  # delete
  /events/delete-event/{eventId}:
    delete:
      parameters:
        # TODO
      tags:
        - "events"
      summary: "Deletes an event"
      description: ""
      responses: 
        # TODO
  
  /events/unsave-event/{eventId}:
    put:
      parameters:
        # TODO
      tags:
        - "events"
      summary: "Unsaves an event for the user"
      description: ""
      responses:
        # TODO

 
# ARMIES LISTS

  # create
  /armies/create-army:
    post:
      parameters:
        # TODO
      tags:
        - "armies"
      summary: "Creates a new army"
      description: ""
      responses:
        # TODO
  
  # read
  /armies/get-armies-list:
    get:
      parameters:
        # TODO
      tags:
        - "armies"
      summary: "Retrieves the user's armies list"
      description: ""
      responses:
        # TODO
  
  /armies/get-army/{armyId}:
    get:
      parameters:
        # TODO
      tags:
        - "armies"
      summary: "Retrieves an army data"
      description: ""
      responses:
        # TODO
      
  
  # update
  /armies/update-army/{armyId}:
    put:
      parameters:
        # TODO
      tags:
        - "armies"
      summary: "Updates an army"
      description: "Updates an army"
      responses:
        # TODO
      
  # delete
  
  /armies/delete-army/{armyId}:
    delete:
      parameters:
        # TODO
      tags:
        - "armies"
      summary: "Deletes an army"
      description: "Deletes an army"
      responses:
        # TODO

# ARMIES TAGS
  
  # create
  /armies/tags/create-tag:
    post:
      parameters:
        # TODO
      tags:
        - "armies"
      summary: "Creates an army tag"
      descrition: "Creates an army tag"
      responses:
        # TODO
  
  # read
  /armies/tags/get-tags-list:
    get:
      parameters:
        # TODO
      tags: 
        - "armies"
      summary: "Retrieves the user's armies tags list"
      description:
      responses:
        # TODO
  
  /armies/tag/get-tag/{tagId}:
    get:
      parameters:
        # TODO
      tags:
        - "armies"
      summary: "Retrieves a tag data"
      description: ""
      responses:
        # TODO
      
  # update
  /armies/tag/update-tag/{tagId}:
    put:
      parameters:
        # TODO
      tags:
        - "armies"
      summary: "Updates an army tag"
      description: ""
      responses: 
        # TODO
  
  # delete
  /armies/tag/delete-tag/{tagId}:
    delete:
      parameters:
        # TODO
      tags:
        - "armies"
      summary: "Deletes an army tag"
      description: ""
      responses:
        # TODO
 
  
# PROPHECIES

  # read
  /prophecies/get-prophecy:
    get:
      parameters:
        # TODO
      tags:
        - "prophecies"
      summary: "Retrieves a prophecy for the user"
      description: ""
      responses:
        # TODO
  
  /prophecies/get-history:
    get:
      parameters:
        # TODO
      tags:
        - "prophecies"
      summary: "Retrieves the prophecies histrory"
      description: ""
      responses:
        # TODO

  
# STATISTICS

  # create
  /statistics/create-statistic:
    post:
      parameters:
        # TODO
      tags:
        - "statistics"
      summary: "Creates a new statistic"
      descirption: ""
      
  # read
  /statistics/get-statistics-list:
    get:
      parameters:
        # TODO
      tags:
        - "statistics"
      summary: "Retrieves the user's statistics list"
      description: ""
      responses:
        # TODO
        
  /statistics/get-statistic/{statisticId}:
    get:
      parameters:
        # TODO
      tags:
        - "statistics"
      summary: "Retrieves a statistic data"
      description: ""
      responses:
        # TODO
  
  # update    
  /statistics/update-statistic/{statisticId}:
    put:
      parameters:
        # TODO
      tags:
        - "statistics"
      summary: "Updates a statistic"
      description: ""
      responses:
        # TODO
      
  # delete
  /statistics/delete-statistic/{statisticId}:
    delete:
      parameters:
        # TODO
      tags:
        - "statistics"
      summary: "Deletes a statistic"
      description: ""
      responses:
        # TODO
  

# SETTINGS

  # update
  /settings/account/update-password:
    put:
      parameters:
        # TODO
      tags:
        - "settings"
      summary: "Updates the user's password"
      description: ""
      responses:
        # TODO
  
  /settings/account/update-username:
    put:
      parameters:
        # TODO
      tags:
        - "settings"
      summary: "Updates the user's username"
      description: ""
      responses:
        # TODO

  /settings/account/update-profile-picture:
    put:
      parameters:
        # TODO
      tags:
        - "settings"
      summary: "Updates the user's profile picture"
      description: ""
      responses: 
        # TODO
  
  /settings/account/update-email-address:
    put:
      parameters:
        # TODO
      tags:
        - "settings"
      summary: "Updates the user's email address"
      description: ""
      responses: 
        # TODO
  
  # delete
  /settings/account/delete-account:
    delete:
      parameters:
        # TODO
      tags:
        - "settings"
      summary: "Deletes the user's account"
      description: ""
      responses:
        # TODO
      
      
# TEAMS

  # create
  /teams/create-team:
    post:
      parameters:
        # TODO
      tags:
        - "teams"
      summary: "Creates a new team"
      description: ""
      responses:
        # TODO
        
  /teams/{teamId}/create-message:
    put:
      parameters:
        # TODO
      tags:
        - "teams"
      summary: "Creates a new message in the team"
      description: ""
      responses:
        # TODO  
      
  # read
  /teams/get-teams-list:
    get:
      parameters:
        # TODO
      tags:
        - "teams"
      summary: "Retrieves the user's teams list"
      description: ""
      responses:
        # TODO
  
  /teams/get-team/{teamId}:
    get:
      parameters:
        # TODO
      tags:
        - "teams"
      summary: "Retrieves a team data"
      description: ""
      responses:
        # TODO
        
  /teams/{teamId}/get-messages:
    get:
      parameters:
        # TODO
      tags:
        - "teams"
      summary: "Retrieves the team's messages"
      description: ""
      responses:
        # TODO
        
  # update
  /teams/rename-team/{teamId}:
    put:
      parameters:
        # TODO
      tags:
        - "teams"
      summary: "Renames a team"
      description: ""
      responses:
        # TODO
        
  /teams/{teamId}/update-message/{messageId}:
    put:
      parameters:
        # TODO
      tags:
        - "teams"
      summary: "Updates a team's message"
      description: ""
      responses:
        # TODO
  
  /teams/{teamId}/invite-user/{userId}:
    put:
      parameters: 
        # TODO
      tags:
        - "teams"
      summary: "Invites a user in a team"
      description: ""
      responses:
        # TODO
      
    /teams/{teamId}/respond-to-invitation:
      put:
        parameters:
          # TODO
        tags:
          - "teams"
        summary: "Sends a response to a team invitation"
        description: ""
        responses:
          # TODO
          
    # delete
    /teams/delete-team/{teamId}:
      delete:
        parameters:
          # TODO
        tags:
          - "teams"
        summary: "Deletes a team"
        description: ""
        responses:
          # TODO
      
  /teams/{teamId}/delete-message/{messageId}:
    delete:
      parameters:
        # TODO
      tags:
        - "teams"
      summary: "Deletes a team's message"
      description: ""
      responses:
        # TODO


# UNITS
  
  # create
  /units/create-unit:
    post:
      parameter:
        # TODO
      tags:
        - "units"
      summary: "Creates a unit"
      description: ""
      responses:
        # TODO
  
  # read
  /units/get-units-list:
    get:
      parameters:
        # TODO
      tags:
        - "units"
      summary: "Retrieves the user's units list"
      descriptions: ""
      responses:
        # TODO
  
  /units/get-unit/{unitId}:
    get:
      parameters:
        # TODO
      tags:
        - "units"
      summary: "Retrieves a unit data"
      description: ""
      responses:
        # TODO
  
  # update
  /units/update-unit/{unitId}:
    put:
      parameters:
        # TODO
      tags:
        - "units"
      summary: "Updates a unit"
      description: ""
      responses:
        # TODO
  
  # delete
  /units/delete-unit/{unitId}:
    delete:
      parameters:
        # TODO
      tags:
        - "units"
      summary: "Deletes a unit"
      description: ""
      responses:
        # TODO
  

# Users

  # create

  # read
  /users/get-users-list:
    get:
      parameters:
        # TODO
      tags:
        - "users"
      summary: "Retrieves a users list"
      description: ""
      responses: 
        # TODO
        
  /users/get-user/{userId}:
    get:
      parameters:
        # TODO
      tags:
        - "users"
      summary: "Retrieves a user data"
      description: ""
      responses:
        # TODO
        
  /users/get-blocked-users-list:
    get:
      parameters:
        # TODO
      tags:
        - "users"
      summary: "Retrieves the blocked users list"
      description: ""
      responses:
        # TODO
        
  /users/{userId}/profile/statistics/get-shared-statistics-list:
    put:
      parameters:
        # TODO
      tags:
        - "users"
      summary: "Retrieves the list of shared statistics"
      description: ""
      responses:
        # TODO
        
  /users/{userId}/profile/armies/get-shared-armies-list:
    get:
      parameters:
        # TODO
      tags:
        - "users"
      summary: "Retrieves the shared armies list"
      description: ""
      responses:
        # TODO
      
  /users/{userId}/profile/pictures/get-shared-pictures-list:
    get:
      parameters:
        # TODO
      tags:
        - "users"
      summary: "Retreves the shared pictures list"
      description: ""
      responses:
        # TODO
      
  /users/profile/pictures/get-sared-picture/{pictureId}:
    get:
      parameters:
        # TODO
      tags:
        - "users"
      summary: "Retrieves a shared picture data"
      description: ""
      responses:
        # TODO
  
  /users/{userId}/profile/followers/get-followers-list:
    get:
      parameters:
        # TODO
      tags:
        - "users"
      summary: "Retrieves a user followers list"
      description: ""
      responses:
        # TODO
    
  /users/{userId}/profile/followers/get-followed-users-list:
    get:
      parameters:
        # TODO
      tags:
        - "users"
      summary: "Retrieves the followed users list"
      description: ""
      responses:
        # TODO
        
  #update
  /users/follow-user/{userId}:
    put:
      parameters:
        # TODO
      tags:
        - "users"
      summary: "Follows a user"
      description: ""
      responses:
        # TODO

  /users/unfollow-user/{userId}:
    put:
      parameters:
        # TODO
      tags:
        - "users"
      summary: "Unfollows a user"
      description: ""
      responses:
        # TODO

  /users/block-user/{userId}:
    put:
      parameters:
        # TODO
      tags:
        - "users"
      summary: "Blocks a user"
      description: ""
      responses:
        # TODO

  /users/unblock-user/{userId}:
    put:
      parameters:
        # TODO
      tags:
        - "users"
      summary: "Unblocks a user"
      description: ""
      responses:
        # TODO

  /users/profile/statistics/share-statistic/{statisticId}:
    put:
      parameters:
        # TODO
      tags:
        - "users"
      summary: "Shares a statistic"
      description: ""
      responses:
        # TODO

  /users/profile/statistics/unshare-statistic/{statisticId}:
    put:
      parameters:
        # TODO
      tags:
        - "users"
      summary: "Unshares a statistic"
      description: ""
      responses:
        # TODO

  /users/profile/armies/share-army/{armyId}:
    put:
      parameters:
        # TODO
      tags:
        - "users"
      summary: "Shares an army list"
      description: ""
      responses:
        # TODO

  /users/profile/armies/unshare-army/{armyId}:
    put:
      parameters:
        # TODO
      tags:
        - "users"
      summary: "Unshares an army list"
      description: ""
      responses:
        # TODO

  /users/profile/pictures/share-picture:
    put:
      parameters:
        # TODO
      tags:
        - "users"
      summary: "Shares a picture"
      description: ""
      responses:
        # TODO

  /users/profile/pictures/unshare-picture/{pictureId}:
    delete:
      parameters:
        # TODO
      tags:
        - "users"
      summary: "Unshares a picture"
      description: ""
      responses:
        # TODO

# Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com
basePath: /Victoire-Rabeau/Prophecy/1.0.0
schemes:
 - https