swagger: "2.0"
info:
  description: |
    This is the Prophecy Api documentation
  version: 1.0.0
  title: "Prophecy Api"

# host: "localhost" # TODO: change

# basePath: "/api"

tags:
  - name: "account"
    description: "Everything about the user's account"
  - name: "events"
    description: "Everything about the events"
  - name: "armies"
    description: "Everything about the armies"
  - name: "prophecies"
    description: "Everything about the prophecies"
  - name: "statistics"
    description: "Everything about the statistics"
  - name: "settings"
    description: "Everything about the settings"
  - name: "chats"
    description: "Everything about the chats"
  - name: "users"
    description: "Everything about the users"
  - name: "armies tags"
    description: "Everything about the armies tags"
  - name: "units"
    description: "Everything about the units"

# schemes:
#   - "http"
#   - "https"


paths:

# Account: 

  /account/sign-in:
    post:
      parameters:
        - name: "username"
          in: "body"
          description: "The user's username"
          required: true
          type: "string"
        - name: "password"
          in: "body"
          description: "The user's password"
          required: true
          type: string
      tags: 
        - "account"
      summary: "Enables the user to sign in"      
      description: "Enables the user to sign in"
      responses:
        # TODO
        
  /account/sign-up:
    post:
      parameters:
        # TODO
      tags: 
        - "account"
      summary: "Enables the user to create an account"
      description: "Enables the user to create an account"
      responses: 
        # TODO
        
  /account/sign-out:
    get:
      parameters:
        # TODO
      tags:
        - "account"
      summary: "Enables the user to logout"
      description: "Enables the user to logout"
      responses:
        # TODO

# EVENTS

  # create
  /events/create-event:
    post:
      parameters:
        # TODO
      tags:
        - "events"
      summary: "Creates a new event"
      description: "Creates a new event"
      responses:
        # TODO
        
  /events/save-event:
    post:
      parameters:
        # TODO
      tags:
        - "events"
      summary: "Saves an event for the user"
      description: "Saves an event for the user"
      responses: 
        # TODO

  # read
  /events/get-events:
    get:
      parameters:
        #TODO
      tags:
        - "events"
      summary: "Retrieves the events"
      description: "Retrieves the events"
      responses:
        # TODO
  
  /events/get-saved-events:
    get:
      parameters:
        # TODO
      tags:
        - "events"
      summary: "Retrieves the saved events"
      description: "Retrieves the saved events"
      responses: 
        # TODO
  
  # update
  /event/update-event:
    put:
      parameters:
        # TODO
      tags:
        - "events"
      summary: "Updates an event's informations"
      description: "Updates an event's informations"
      responses:
        # TODO

  # delete
  /events/delete-event/:
    delete:
      parameters:
        # TODO
      tags:
        - "events"
      summary: "Deletes an event"
      description: "Deletes an event"
      responses: 
        # TODO
  
  /events/unsave-event:
    delete:
      parameters:
        # TODO
      tags:
        - "events"
      summary: "Unsaves an event for the user"
      description: "Unsaves an event for the user"
      responses:
        # TODO

 
# ARMIES LISTS

  # create
  /armies/create-army:
    post:
      parameters:
        # TODO
      tags:
        - "armies"
      summary: "Creates a new army"
      description: "Creates a new army"
      responses:
        # TODO
  
  # read
  /armies/get-armies:
    get:
      parameters:
        # TODO
      tags:
        - "armies"
      summary: "Retrieves the user's armies"
      description: "Retrieves the user's armies"
      responses:
        # TODO
  
  # update
  /armies/update-army:
    put:
      parameters:
        # TODO
      tags:
        - "armies"
      summary: "Updates an army"
      description: "Updates an army"
      responses:
        # TODO
      
  # delete
  
  /armies/delete-army:
    delete:
      parameters:
        # TODO
      tags:
        - "armies"
      summary: "Deletes an army"
      description: "Deletes an army"
      responses:
        # TODO

# ARMIES TAGS
  
  # create
  /armies/tags/create-tag:
    post:
      parameters:
        # TODO
      tags:
        - "armies tags"
      summary: "Creates an army tag"
      descrition: "Creates an army tag"
      responses:
        # TODO
  
  # read
  /armies/tags/get-tags:
    get:
      parameters:
        # TODO
      tags: 
        - "armies tags"
      summary: "Retrieves the user's armies tags"
      description:
      
  # update
  /armies/tag/update-tag:
    put:
      parameters:
        # TODO
      tags:
        - "armies tags"
      summary: "Updates an army tag"
      description: ""
      responses: 
        # TODO
  
  # delete
  /armies/tag/delete-tag/{tagId}:
    delete:
      parameters:
        # TODO
      tags:
        - "armies tags"
      summary: "Deletes an army tag"
      description: ""
      responses:
        # TODO
 
  
# Prophecies

  # read
  /prophecies/get-prophecy:
    get:
      parameters:
        # TODO
      tags:
        - "prophecies"
      summary: "Retrieves a prophecy for the user"
      description: ""
      responses:
        # TODO
  
  /prophecies/get-history:
    get:
      parameters:
        # TODO
      tags:
        - "prophecies"
      summary: "Retrieves the prophecies histrory"
      description: ""
      responses:
        # TODO

  
# STATISTICS

  # create
  /statistics/create-statistic:
    post:
      parameters:
        # TODO
      tags:
        - "statistics"
      summary: "Creates a new statistic"
      descirption: ""
      
  # read
  /statistics/get-statistics:
    get:
      parameters:
        # TODO
      tags:
        - "statistics"
      summary: "Retrieves the user's statistics"
      description: ""
      responses:
        # TODO
  
  # update    
  /statistics/update-statistic:
    put:
      parameters:
        # TODO
      tags:
        - "statistics"
      summary: "Updates a statistic"
      description: ""
      responses:
        # TODO
      
  # delete
  /statistics/delete-statistic:
    delete:
      parameters:
        # TODO
      tags:
        - "statistics"
      summary: "Deletes a statistic"
      description: ""
      responses:
        # TODO
  

# SETTINGS

  # update
  /settings/account/update-password:
    put:
      parameters:
        # TODO
      tags:
        - "settings"
      summary: "Updates the user's password"
      description: ""
      responses:
        # TODO
  
  /settings/account/update-username:
    put:
      parameters:
        # TODO
      tags:
        - "settings"
      summary: "Updates the user's username"
      description: ""
      responses:
        # TODO

  /settings/account/update-profile-picture:
    put:
      parameters:
        # TODO
      tags:
        - "settings"
      summary: "Updates the user's profile picture"
      description: ""
      responses: 
        # TODO
  
  /settings/account/update-email-address:
    put:
      parameters:
        # TODO
      tags:
        - "settings"
      summary: "Updates the user's email address"
      description: ""
      responses: 
        # TODO
  
  # delete
  /settings/account/delete-account:
    delete:
      parameters:
        # TODO
      tags:
        - "settings"
      summary: "Deletes the user's account"
      description: ""
      responses:
        # TODO
      
  
# Chat

  /chat/conversation/get-conversations:

  /chat/conversation/create-conversation:
  
  /chat/conversation/delete-conversaton/{conversationId}:
  
  /chat/conversation/update-conversation/{conversationId}:
  
  /chat/conversation/{conversationId}/add-user/{userId}:
  
  /chat/conversation/{conversationId}/remove-user/{userId}:
  
  /chat/conversation/{conversationId}/add-message:
  
  /chat/conversation/{conversationId}/delete-message/{messageId}:
  
  /chat/conversation/{conversationId}/update-message/{messageId}:
  
  
# Users

  /users/get-users:

  /users/follow-user:

  /users/unfollow-user:

  /users/block-user:

  /users/unblock-user:

  /users/get-blocked-users:

  /users/profile/get-profile-informations:

  /users/profile/statistics/share-statistic:

  /users/profile/statistics/unshare-statistic:

  /users/profile/statistics/get-shared-statistics:

  /users/profile/armies/share-army:

  /users/profile/armies/unshare-army:

  /users/profile/armies/get-shared-armies:

  /users/profile/pictures/share-picture:

  /users/profile/pictures/unshare-picture:

  /users/profile/pictures/get-shared-pictures:

  /users/profile/followers/get-followers:
# Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com
basePath: /Victoire-Rabeau/Prophecy-api/1.0.0
schemes:
 - https