on: [ pull_request ]
jobs:
  build:
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build server
        run: | 
          echo "PORT=3000" > .env
          docker-compose -f docker-compose.yml up -d
