on: [ pull_request ]
jobs:
  build:
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: install
        run: |
          printf "PORT=${{ secrets.PORT }}\nIP=${{ secrets.IP }}" > .env
          yarn

      - name: run
        run: | 
          docker-compose -f docker-compose.yml up -d

      - name: unit tests
        run: |
          yarn test --coverage
