name: "Deploy"
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: "Setup environement"
        run: |
          printf "SERVER_PORT=${{ secrets.SERVER_PORT }}\nPOSTGRES_DB=${{ secrets.POSTGRES_DB }}\nPOSTGRES_USER=${{ secrets.POSTGRES_USER }}\nPOSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}\nDATABASE_IP=${{ secrets.DATABASE_IP_AWS }}\nDATABASE_PORT=${{ secrets.DATABASES_PORT }}\nPGADMIN_PORT=${{ secrets.PGADMIN_PORT }}\nPGADMIN_DEFAULT_EMAIL=${{ secrets.PGADMIN_DEFAULT_EMAIL }}\nPGADMIN_DEFAULT_PASSWORD=${{ secrets.PGADMIN_DEFAULT_PASSWORD }}\nPGADMIN_LISTEN_ADDRESS=${{ secrets.PGADMIN_LISTEN_ADDRESS }}\nPGADMIN_LISTEN_PORT=${{ secrets.PGADMIN_LISTEN_PORT }}\nJWT_SECRET=${{ secrets.JWT_SECRET }}\nTESTS_PORT=${{ secrets.TESTS_PORT }}\n" > .env
      - name: "Configure AWS credentials"
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: 032910807353.dkr.ecr.us-east-1.amazonaws.com
        run: |
          docker build -t $REPOSITORY/prophecy_backend:v0.$GITHUB_RUN_NUMBER.0 .
          docker push $REPOSITORY/prophecy_backend:v0.$GITHUB_RUN_NUMBER.0
