name: "Deploy development"
on:
  push:
    branches:
      - dev

cjobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: "Setup environement"
        run: |
          printf "SERVER_PORT=${{ secrets.SERVER_PORT }}\n
          POSTGRES_DB=${{ secrets.DEV_DATABASE_NAME }}\n
          POSTGRES_USER=${{ secrets.DEV_DATABASE_USER }}\n
          POSTGRES_PASSWORD=${{ secrets.DEV_DATABASE_PASSWORD }}\n
          DATABASE_IP=${{ secrets.DEV_DATABASE_IP }}\n
          DATABASE_PORT=${{ secrets.DATABASE_PORT }}\n
          JWT_SECRET=${{ secrets.JWT_SECRET }}\n
          TESTS_PORT=${{ secrets.TESTS_PORT }}\n
          MIGRATION_PORT=${{ secrets.MIGRATION_PORT }}\n
          SES_REGION=${{ secrets.AWS_SES_REGION }}\n
          SES_ACCESS_KEY=${{ secrets.AWS_SES_ACCESS_KEY }}\n
          SES_SECRET_ACCESS_KEY=${{ secrets.AWS_SES_SECRET_ACCESS_KEY }}\n
          SES_FROM_ADDRESS=${{ secrets.AWS_SES_FROM_ADDRESS }}\n
          API_URL=${{ secrets.DEV_API_URL }}\n
          MATHS_KEY=${{ secrets.MATHS_KEY }}\n
          WEBSITE_URL=${{ secrets.DEV_WEBSITE_URL }}\n" > .env
      - name: "Configure AWS credentials"
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: 032910807353.dkr.ecr.us-east-1.amazonaws.com
        run: |
          docker build -t $REPOSITORY/prophecy_backend:dev -f .devcontainers/backend-production.Dockerfile
          docker push $REPOSITORY/prophecy_backend:dev
